apiVersion: "v1"
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name:  tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: danushk97/tasks-demo-api
          env:
            - name: TASKS_FOLDER
              value: "tasks"
            - name: AUTH_ADDRESS
              value: "auth-service.default"
